eureka:
  client:
    #配置链注册中心地址
    service-url:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10002
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1
  #配置链路追踪地址
  zipkin:
    base-url: http://118.126.104.111:9411/
#配置路由网关请求接口
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service