server:
  #端口10002
  port: 10002

spring:
  application:
    name: eureka-client-tow

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"